name: Daily publish 3 from leetcode-backup

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target (LeetCode)
        uses: actions/checkout@v4

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure dirs and manifest
        run: |
          mkdir -p published
          touch .published_hashes.txt

      - name: Checkout source (leetcode-backup)
        uses: actions/checkout@v4
        with:
          repository: gauravmidha/leetcode-backup
          token: ${{ secrets.SRC_TOKEN }}
          path: src
          fetch-depth: 1

      - name: Publish up to 3 unseen files
        shell: bash
        run: |
          set -euo pipefail
          moved=0
          mapfile -t files < <(find src -type f -not -path "*/.git/*" | sort)
          for f in "${files[@]}"; do
            h=$(sha256sum "$f" | awk '{print $1}')
            grep -Fxq "$h" .published_hashes.txt && continue
            rel="${f#src/}"
            dst="published/$rel"
            mkdir -p "$(dirname "$dst")"
            [[ -f "$dst" ]] && {
              b="$(basename "$dst")"; d="$(dirname "$dst")"; n="${b%.*}"; e="${b##*.}"
              [[ "$e" == "$b" ]] && dst="$d/${n}_dup_$(date +%s)" || dst="$d/${n}_dup_$(date +%s).$e"
            }
            cp -n "$f" "$dst"
            echo "$h" >> .published_hashes.txt
            git add .published_hashes.txt "$dst"
            (( ++moved >= 3 )) && break
          done
          if [[ $moved -gt 0 ]]; then
            git commit -m "Daily publish: $moved file(s) from leetcode-backup"
            git push
          else
            echo "No new files to publish."
          fi
